/*
 * This source file was generated by the Gradle 'init' task
 */
package inventario;

public class App {
    public String getGreeting() {
        return "Hola Mundo 4!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
